### ISSUE TITLE
eventdetails activity

### ISSUE THREAD

**Issue by fshafi1997** [kvosbur/Lambency-Client#13]
Lucas I created a new activity that is able to send sms for event sharing. the sms activity is working fine. I also added a share event button in the eventdetailsactivity yu had created and then in the main of the activity i said if that share button is pressed go to the sms activity. 
Can you pls take a look at why the eventdetails activity is not running but its preview looks fine. 
If it runs then all will be fine becauase the sms activity is working. 

Thanks...

**Comment by lshanker** [comment]
Hey Farhan, it's fixed now. I think the problem was that you had the onclick listener for your button in the wrong spot. The easiest way to listen for button clicks is to use ButterKnife with @OnClick, so I just switched it to that. 

Also, the SMS activity did not work for me and the button didn't take me to the new activity. I was always thinking we'd have something like [this](https://developer.android.com/training/sharing/shareaction.html) for sharing instead of a separate activity, but if you don't have time to change it it's probably fine.
